<template>
  <iframe
    src="https://hiplotdev.hiplot.com.cn/idbview/other/SeuratV3Wizard/shiny/"
    allowfullscreen="true"
    webkitallowfullscreen="true"
    mozallowfullscreen="true"
    oallowfullscreen="true"
    msallowfullscreen="true"
  />
</template>
<script></script>
